server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jptaxi}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=${DB_INIT_MODE:never}
spring.sql.init.schema-locations=${DB_SCHEMA_LOCATION:file:../database/schema.sql}
spring.sql.init.data-locations=${DB_DATA_LOCATION:file:../database/data.sql}

spring.web.resources.static-locations=classpath:/static/,file:../frontend/
jptaxi.upload-dir=${UPLOAD_DIR:../frontend/uploads}
