import { createContext, useContext, useMemo, useState } from 'react';

const LANGUAGE_KEY = 'jpTaxiLanguage';

const dictionaries = {
  ja: {
    navHome: 'ホーム',
    navAccount: 'アカウント',
    navMessages: 'メッセージ',
    homeGreeting: 'こんにちは！',
    homeQuestion: 'どこへ行きますか?',
    homeSearchTitle: 'どこへ行きますか？',
    homeSearchCopy: '目的地・住所を入力、または履歴から選択',
    quickWork: '職場',
    quickHome: '自宅',
    quickFavorite: 'お気に',
    quickMore: 'もっと見る',
    callTaxiNow: '今すぐタクシーを呼ぶ',
    bookNow: 'すぐに予約',
    profileSettings: 'プロフィール設定',
    languageSettings: '言語設定',
    displayLanguage: '表示言語',
    japanese: '日本語',
    vietnamese: 'Tiếng Việt',
    saveChanges: '変更を保存',
    saved: '保存しました',
    quickAddress: 'クイック住所',
    saveAddress: '住所を保存',
    routeConfirmTitle: '予約内容を確認',
    routeConfirmCopy: '最終的なルートと料金を確認してください。',
    pickupRoute: '乗車ルート',
    pickupPoint: '出発地',
    destination: '目的地',
    currentLocation: '現在位置',
    rideTime: '乗車予定',
    now: '現在',
    duration: '所要時間',
    distance: '走行距離',
    vehicleType: '車種',
    standard: 'スタンダード',
    standardCopy: '快適なセダン・禁煙車',
    memoToDriver: 'ドライバーへのメモ (任意)',
    memoPlaceholder: '例: 大きな荷物があります、または待ち合わせ場所の詳細など...',
    fareDetails: '料金詳細',
    baseFare: '基本運賃',
    distanceFare: '距離加算',
    bookingFee: '予約手数料',
    totalFare: '合計金額',
    selfBooking: '自分用',
    proxyBooking: '代理予約',
    back: '戻る',
    confirmBooking: '予約を確定する',
    locationSearchTitle: '目的地を検索',
    locationSearchCopy: '目的地を入力するか、履歴から選択してください。',
    search: '検索',
    destinationPlaceholder: '目的地・住所を入力',
    recentHistory: '最近の履歴',
    searchResults: '検索結果',
    continueWithDestination: 'この目的地で続ける',
    routeInfo: 'ルート情報',
    calculating: '計算中',
    searchingTaxi: 'タクシーを呼び出し中',
    checkingNearbyCars: '近くの車両を確認しています...',
    nearbyCarsFoundPrefix: '近くに',
    nearbyCarsFoundSuffix: '台の車両が見つかりました。ドライバーの応答を待っています。',
    driverConfirm: 'ドライバー確認へ',
    cancel: 'キャンセル',
    etaLabel: '到着予定時間',
    remainingPrefix: 'あと',
    callDriver: '電話する',
    messageDriver: 'メッセージ',
    driverName: '田中 ドライバー',
    driverCar: 'トヨタ・ヴィオス (黒)',
    profileMenu: 'プロフィールメニュー',
    profile: 'プロフィール',
    security: 'セキュリティ',
    notifications: '通知設定',
    paymentMethod: '支払い方法',
    logout: 'ログアウト',
    profileCopy: '個人情報やアカウント設定を管理できます。必要に応じて内容を更新してください。',
    personalInfo: '個人情報',
    surname: '姓',
    givenName: '名',
    emailAddress: 'メールアドレス',
    gender: '性別',
    male: '男性',
    female: '女性',
    phoneNumber: '電話番号',
    address: '住所',
    generalUser: '一般ユーザー',
    accountInfo: 'アカウント情報',
    loginAccount: 'ログインアカウント',
    registeredDate: '登録日',
    passwordChange: 'パスワード変更',
    passwordSecurityCopy: 'アカウント保護のため、定期的にパスワードを更新してください。',
    accountEditCopy: 'ログインID、メール、電話番号などの基本アカウント情報を編集します。',
    loginHistory: 'ログイン履歴',
    loginHistoryCopy: '最近ログインした端末と日時を確認できます。',
    twoFactor: '二段階認証',
    twoFactorCopy: 'ログイン時に追加の確認コードを要求して、セキュリティを強化します。',
    edit: '編集する',
    change: '変更する',
    check: '確認する',
    configure: '設定する',
    defaultPaymentMethod: '既定の支払い方法',
    addCard: 'カードを追加',
    logoutCopy: '現在のアカウントからログアウトします。',
    saveContentCopy: '内容を確認して保存してください。',
    loginId: 'ログインID',
    displayName: '表示名',
    currentPassword: '現在のパスワード',
    newPassword: '新しいパスワード',
    confirmNewPassword: '新しいパスワード確認',
    changeAccountInfo: 'アカウント情報を編集',
    changeAvatar: 'プロフィール画像を変更',
    cardInfo: 'カード情報',
    logoutConfirm: 'ログアウト確認',
    inputAddressFor: 'の住所を入力',
    dispatchNotification: '配車通知',
    dispatchNotificationCopy: '予約確認や到着予定などの通知を受け取る',
    messageNotification: 'メッセージ通知',
    messageNotificationCopy: 'ドライバーやサポートからの連絡を受け取る',
    emailNotification: 'メール通知',
    emailNotificationCopy: 'キャンペーンやお知らせをメールで受け取る',
    languagePageCopy: 'アプリ全体の表示言語を選択できます。変更はこのブラウザに保存されます。',
    currentLanguage: '現在の言語',
    languageOptionJapaneseCopy: '予約、地図、プロフィールを日本語で表示します。',
    languageOptionVietnameseCopy: 'Hiển thị đặt xe, bản đồ và hồ sơ bằng tiếng Việt.',
    savedInBrowser: 'このブラウザに保存',
    paymentPageCopy: '予約で利用する支払い方法を管理します。既定のカードは決済画面に反映されます。',
    activeCard: '利用中のカード',
    expires: '有効期限',
    billingSecurity: '決済の安全性',
    billingSecurityCopy: 'カード情報はデモ表示です。実運用では決済プロバイダー側で安全に保存します。',
    logoutPageCopy: 'ログアウトすると、この端末でのセッションが終了します。保存したクイック住所はこのブラウザに残ります。',
    logoutQuestion: 'ログアウトしますか？',
    confirmLogoutCopy: '現在のセッションを終了してログイン画面に戻ります。',
    yesLogout: 'はい、ログアウト',
    noCancel: 'いいえ',
    signedInAs: 'ログイン中',
    stayLoggedIn: 'ログインを続ける',
    locationUnavailable: '現在位置を取得できません',
    locationUnavailableCopy: 'ブラウザの位置情報を許可するか、出発地を手動で選択してください。',
    enableLocation: '位置情報を許可すると続行できます',
    routeLongWarning: '長距離のため、所要時間と料金が変動する可能性があります。',
    routeTooFarWarning: 'この目的地はサービス範囲を超えています。70km以内の目的地を選択してください。',
    invalidDestination: '有効な目的地を選択してください。',
    deleteHistory: '削除',
  },
  vi: {
    navHome: 'Trang chủ',
    navAccount: 'Tài khoản',
    navMessages: 'Tin nhắn',
    homeGreeting: 'Xin chào!',
    homeQuestion: 'Bạn muốn đi đâu?',
    homeSearchTitle: 'Bạn muốn đi đâu?',
    homeSearchCopy: 'Nhập điểm đến, địa chỉ hoặc chọn từ lịch sử',
    quickWork: 'Cơ quan',
    quickHome: 'Nhà riêng',
    quickFavorite: 'Yêu thích',
    quickMore: 'Xem thêm',
    callTaxiNow: 'Gọi taxi ngay',
    bookNow: 'Đặt ngay',
    profileSettings: 'Cài đặt hồ sơ',
    languageSettings: 'Cài đặt ngôn ngữ',
    displayLanguage: 'Ngôn ngữ hiển thị',
    japanese: '日本語',
    vietnamese: 'Tiếng Việt',
    saveChanges: 'Lưu thay đổi',
    saved: 'Đã lưu',
    quickAddress: 'Địa chỉ nhanh',
    saveAddress: 'Lưu địa chỉ',
    routeConfirmTitle: 'Xác nhận đặt xe',
    routeConfirmCopy: 'Vui lòng kiểm tra lộ trình và giá cuối cùng.',
    pickupRoute: 'Lộ trình',
    pickupPoint: 'Điểm đón',
    destination: 'Điểm đến',
    currentLocation: 'Vị trí hiện tại',
    rideTime: 'Thời gian đón',
    now: 'Hiện tại',
    duration: 'Thời gian',
    distance: 'Quãng đường',
    vehicleType: 'Loại xe',
    standard: 'Tiêu chuẩn',
    standardCopy: 'Sedan thoải mái, không hút thuốc',
    memoToDriver: 'Ghi chú cho tài xế (tuỳ chọn)',
    memoPlaceholder: 'Ví dụ: Tôi có hành lý lớn hoặc chi tiết điểm hẹn...',
    fareDetails: 'Chi tiết giá',
    baseFare: 'Giá cơ bản',
    distanceFare: 'Phụ phí quãng đường',
    bookingFee: 'Phí đặt xe',
    totalFare: 'Tổng tiền',
    selfBooking: 'Cho bản thân',
    proxyBooking: 'Đặt hộ',
    back: 'Quay lại',
    confirmBooking: 'Xác nhận đặt xe',
    locationSearchTitle: 'Tìm điểm đến',
    locationSearchCopy: 'Nhập điểm đến hoặc chọn từ lịch sử.',
    search: 'Tìm kiếm',
    destinationPlaceholder: 'Nhập điểm đến hoặc địa chỉ',
    recentHistory: 'Lịch sử gần đây',
    searchResults: 'Kết quả tìm kiếm',
    continueWithDestination: 'Tiếp tục với điểm đến này',
    routeInfo: 'Thông tin lộ trình',
    calculating: 'Đang tính',
    searchingTaxi: 'Đang gọi taxi',
    checkingNearbyCars: 'Đang kiểm tra xe gần bạn...',
    nearbyCarsFoundPrefix: 'Tìm thấy',
    nearbyCarsFoundSuffix: 'xe gần bạn. Đang chờ tài xế phản hồi.',
    driverConfirm: 'Xác nhận tài xế',
    cancel: 'Hủy',
    etaLabel: 'Thời gian đến dự kiến',
    remainingPrefix: 'Còn',
    callDriver: 'Gọi điện',
    messageDriver: 'Nhắn tin',
    driverName: 'Tài xế Tanaka',
    driverCar: 'Toyota Vios (đen)',
    profileMenu: 'Menu hồ sơ',
    profile: 'Hồ sơ',
    security: 'Bảo mật',
    notifications: 'Thông báo',
    paymentMethod: 'Phương thức thanh toán',
    logout: 'Đăng xuất',
    profileCopy: 'Quản lý thông tin cá nhân và cài đặt tài khoản. Cập nhật nội dung khi cần.',
    personalInfo: 'Thông tin cá nhân',
    surname: 'Họ',
    givenName: 'Tên',
    emailAddress: 'Email',
    gender: 'Giới tính',
    male: 'Nam',
    female: 'Nữ',
    phoneNumber: 'Số điện thoại',
    address: 'Địa chỉ',
    generalUser: 'Người dùng thường',
    accountInfo: 'Thông tin tài khoản',
    loginAccount: 'Tài khoản đăng nhập',
    registeredDate: 'Ngày đăng ký',
    passwordChange: 'Đổi mật khẩu',
    passwordSecurityCopy: 'Hãy cập nhật mật khẩu định kỳ để bảo vệ tài khoản.',
    accountEditCopy: 'Chỉnh sửa ID đăng nhập, email, số điện thoại và thông tin tài khoản cơ bản.',
    loginHistory: 'Lịch sử đăng nhập',
    loginHistoryCopy: 'Kiểm tra thiết bị và thời gian đăng nhập gần đây.',
    twoFactor: 'Xác thực hai bước',
    twoFactorCopy: 'Tăng bảo mật bằng mã xác nhận bổ sung khi đăng nhập.',
    edit: 'Chỉnh sửa',
    change: 'Thay đổi',
    check: 'Kiểm tra',
    configure: 'Thiết lập',
    defaultPaymentMethod: 'Phương thức mặc định',
    addCard: 'Thêm thẻ',
    logoutCopy: 'Đăng xuất khỏi tài khoản hiện tại.',
    saveContentCopy: 'Vui lòng kiểm tra nội dung rồi lưu.',
    loginId: 'ID đăng nhập',
    displayName: 'Tên hiển thị',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmNewPassword: 'Xác nhận mật khẩu mới',
    changeAccountInfo: 'Chỉnh sửa thông tin tài khoản',
    changeAvatar: 'Thay đổi ảnh hồ sơ',
    cardInfo: 'Thông tin thẻ',
    logoutConfirm: 'Xác nhận đăng xuất',
    inputAddressFor: ' - nhập địa chỉ',
    dispatchNotification: 'Thông báo đặt xe',
    dispatchNotificationCopy: 'Nhận thông báo xác nhận đặt xe và thời gian đến dự kiến',
    messageNotification: 'Thông báo tin nhắn',
    messageNotificationCopy: 'Nhận liên hệ từ tài xế và hỗ trợ',
    emailNotification: 'Thông báo email',
    emailNotificationCopy: 'Nhận khuyến mãi và thông báo qua email',
    languagePageCopy: 'Chọn ngôn ngữ hiển thị cho toàn bộ ứng dụng. Thay đổi được lưu trên trình duyệt này.',
    currentLanguage: 'Ngôn ngữ hiện tại',
    languageOptionJapaneseCopy: 'Hiển thị đặt xe, bản đồ và hồ sơ bằng tiếng Nhật.',
    languageOptionVietnameseCopy: 'Hiển thị đặt xe, bản đồ và hồ sơ bằng tiếng Việt.',
    savedInBrowser: 'Đã lưu trong trình duyệt',
    paymentPageCopy: 'Quản lý phương thức thanh toán dùng khi đặt xe. Thẻ mặc định sẽ hiển thị ở màn thanh toán.',
    activeCard: 'Thẻ đang dùng',
    expires: 'Hết hạn',
    billingSecurity: 'Bảo mật thanh toán',
    billingSecurityCopy: 'Thông tin thẻ hiện là dữ liệu demo. Khi vận hành thật, dữ liệu nên được lưu an toàn bởi nhà cung cấp thanh toán.',
    logoutPageCopy: 'Đăng xuất sẽ kết thúc phiên trên thiết bị này. Địa chỉ nhanh đã lưu vẫn còn trong trình duyệt.',
    logoutQuestion: 'Bạn có muốn đăng xuất không?',
    confirmLogoutCopy: 'Phiên hiện tại sẽ kết thúc và bạn sẽ quay lại màn đăng nhập.',
    yesLogout: 'Có, đăng xuất',
    noCancel: 'Không',
    signedInAs: 'Đang đăng nhập',
    stayLoggedIn: 'Tiếp tục đăng nhập',
    locationUnavailable: 'Chưa có vị trí cụ thể',
    locationUnavailableCopy: 'Hãy cho phép trình duyệt lấy vị trí hoặc chọn điểm đón thủ công.',
    enableLocation: 'Bật quyền vị trí để tiếp tục',
    routeLongWarning: 'Quãng đường khá xa, thời gian và giá có thể thay đổi.',
    routeTooFarWarning: 'Điểm đến vượt phạm vi phục vụ. Vui lòng chọn điểm đến trong phạm vi 70 km.',
    invalidDestination: 'Vui lòng chọn một điểm đến hợp lệ.',
    deleteHistory: 'Xóa',
  },
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
  const stored = window.localStorage.getItem(LANGUAGE_KEY);
  return stored === 'vi' ? 'vi' : 'ja';
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(getInitialLanguage);

  const value = useMemo(() => {
    function setLanguage(nextLanguage) {
      const safeLanguage = nextLanguage === 'vi' ? 'vi' : 'ja';
      window.localStorage.setItem(LANGUAGE_KEY, safeLanguage);
      setLanguageState(safeLanguage);
    }

    function t(key) {
      return dictionaries[language][key] ?? dictionaries.ja[key] ?? key;
    }

    return { language, setLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }

  return context;
}
